### ISSUE TITLE
Dependencies must be included to the composer.json

### ISSUE THREAD

**Issue by Atsyn** [franzholz/tt_board#4]
When I will try to enable this extension I seelist of required extensions div2007 and tslib_fetce.
Please include those extension in requirement part in the composer.json

**Comment by franzholz** [comment]
But both dependencies are already in composer.json:

https://github.com/franzholz/tt_board/blob/master/composer.json

**Comment by Atsyn** [comment]
Nope: https://monosnap.com/file/qRtoq1Ux2jwxUK3DUw5VgYBISz920B - screenshot from real project.
Or you still not update package in the packagist.org

**Comment by franzholz** [comment]
See packagist.org at:

https://packagist.org/packages/jambagecom/tt-board

There you have all the dependencies:

    v1.10.12 2019-01-21 13:53 UTC

    Requires

        typo3/cms-core: >=7.6.0,<9.4.0
        typo3-ter/div2007: >=1.10.6
        typo3-ter/tslib_fetce: >=0.4.0,<=0.9.0

**Comment by Atsyn** [comment]
Ok, I set version from "*" to "1.10.12" and now I see next:
`-  jambagecom/tt-board v1.10.12 requires typo3-ter/tslib_fetce >=0.4.0,<=0.9.0 -> no matching package found.`

I can't find this package((

**Comment by franzholz** [comment]
done

**Comment by franzholz** [comment]
The package tslib_fetce now exists:

https://packagist.org/packages/jambagecom/tslib-fetce

**Comment by Atsyn** [comment]
Cool.
And now dependency in this package should follow to 
> jambagecom/tslib-fetce
> jambagecom/div2007
because right now it related with:
> typo3-ter/tslib-fetce
> typo3-ter/div2007
=)

**Comment by franzholz** [comment]
Does this patch help here?

https://github.com/franzholz/tt_board/commit/3712848bad9b90463eddebc28beaefa167e5cf0a

**Comment by Atsyn** [comment]
Yes, thx.
But can you up version for this package to.
Because composer still see wrong dependency in the package (v1.10.12): https://packagist.org/packages/jambagecom/tt-board

**Comment by franzholz** [comment]
I have uploaded now a new version 1.10.13:

**Comment by Atsyn** [comment]
Dependence should be "jambagecom/tslib-fetce" not "jambagecom/tslib_fetce"!

**Comment by franzholz** [comment]
I have uploaded now a new version 1.10.14:

https://github.com/franzholz/tt_board/tree/v1.10.14

**Comment by Atsyn** [comment]
Can be closed. All fine! TXH!
